name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: funkysl4p/ut99-server
    steps:
    - name: Set Image Tag
      run: |
        if [[ $GITHUB_REF_NAME == 'main' ]]; then
          echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
        else
          echo "IMAGE_TAG=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
        fi
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: funkysl4p/ut99-server:latest